 version: '2'
 services:
   db:
     image: mdillon/postgis
     volumes:
      - .data/postgres:/var/lib/postgresql/data
   metabase:
     image: metabase/metabase
     volumes:
      - .data/metabase:/tmp
     environment:
      MB_DB_FILE: /tmp/metabase.db
     depends_on:
       - db
     ports:
       - "3000"
   web:
     build: .
     command: bash -c "./manage.py migrate && DJANGO_SETTINGS_MODULE=GuppiesWechat.settings-production gunicorn --workers=8 -b 0.0.0.0:8001 GuppiesWechat.wsgi"
     volumes:
       - .:/code
     ports:
       - "8001"
     depends_on:
       - db
     environment:
       DJANGO_SETTINGS_MODULE: GuppiesWechat.settings-production
